import { z } from "zod";

export const CandidateInput = z.object({
  id: z.string().uuid().optional(),
  full_name: z.string().min(1),
  photo_url: z.string().nullable().optional(),
  current_position: z.string().nullable().optional(),
  current_company: z.string().nullable().optional(),
  area: z.string().nullable().optional(),
  seniority: z.string().nullable().optional(),
  city: z.string().nullable().optional(),
  state: z.string().nullable().optional(),
  country: z.string().nullable().optional(),
  work_model: z.string().nullable().optional(),
  gender: z.string().nullable().optional(),
  salary_expectation: z.number().nullable().optional(),
  salary_min: z.number().nullable().optional(),
  salary_max: z.number().nullable().optional(),

  linkedin_url: z.string().nullable().optional(),
  email: z.string().nullable().optional(),
  phone: z.string().nullable().optional(),
  resume_url: z.string().nullable().optional(),
  transcript: z.string().nullable().optional(),
  recruiter_note: z.string().nullable().optional(),
  internal_notes: z.string().nullable().optional(),
  disc_raw: z.string().nullable().optional(),
  disc_profile: z.string().nullable().optional(),
  disc_scores: z.any().nullable().optional(),
  // AI-generated / editable structured fields
  headline: z.string().nullable().optional(),
  mini_bio: z.string().nullable().optional(),
  full_bio: z.string().nullable().optional(),
  executive_summary: z.any().nullable().optional(),
  specialties: z.any().nullable().optional(),
  main_results: z.any().nullable().optional(),
  achievements: z.any().nullable().optional(),
  main_case: z.any().nullable().optional(),
  strengths: z.any().nullable().optional(),
  work_style: z.string().nullable().optional(),
  professional_moment: z.any().nullable().optional(),
  motivators: z.any().nullable().optional(),
  trajectory: z.any().nullable().optional(),
  education: z.any().nullable().optional(),
  courses: z.any().nullable().optional(),
  languages: z.any().nullable().optional(),
  competencies: z.any().nullable().optional(),
  additional_info: z.any().nullable().optional(),
  inconsistencies: z.any().nullable().optional(),
  ai_profile: z.any().nullable().optional(),
  status: z.string().nullable().optional(),
});
