/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShortlistsIndexRouteImport } from './routes/shortlists.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as ShortlistsNewRouteImport } from './routes/shortlists.new'
import { Route as ShortlistsShortlistIdRouteImport } from './routes/shortlists.$shortlistId'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as PdfCandidateIdRouteImport } from './routes/pdf.$candidateId'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as CandidatesNewRouteImport } from './routes/candidates.new'
import { Route as CandidatesCandidateIdRouteImport } from './routes/candidates.$candidateId'
import { Route as ShortlistsShortlistIdIndexRouteImport } from './routes/shortlists.$shortlistId.index'
import { Route as STokenIndexRouteImport } from './routes/s.$token.index'
import { Route as ShortlistsShortlistIdAnalysisCandidateIdRouteImport } from './routes/shortlists.$shortlistId.analysis.$candidateId'
import { Route as STokenCCandidateIdRouteImport } from './routes/s.$token.c.$candidateId'
import { Route as STokenAnalysisCandidateIdRouteImport } from './routes/s.$token.analysis.$candidateId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistsIndexRoute = ShortlistsIndexRouteImport.update({
  id: '/shortlists/',
  path: '/shortlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistsNewRoute = ShortlistsNewRouteImport.update({
  id: '/shortlists/new',
  path: '/shortlists/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistsShortlistIdRoute = ShortlistsShortlistIdRouteImport.update({
  id: '/shortlists/$shortlistId',
  path: '/shortlists/$shortlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfCandidateIdRoute = PdfCandidateIdRouteImport.update({
  id: '/pdf/$candidateId',
  path: '/pdf/$candidateId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesNewRoute = CandidatesNewRouteImport.update({
  id: '/candidates/new',
  path: '/candidates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesCandidateIdRoute = CandidatesCandidateIdRouteImport.update({
  id: '/candidates/$candidateId',
  path: '/candidates/$candidateId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistsShortlistIdIndexRoute =
  ShortlistsShortlistIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShortlistsShortlistIdRoute,
  } as any)
const STokenIndexRoute = STokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => STokenRoute,
} as any)
const ShortlistsShortlistIdAnalysisCandidateIdRoute =
  ShortlistsShortlistIdAnalysisCandidateIdRouteImport.update({
    id: '/analysis/$candidateId',
    path: '/analysis/$candidateId',
    getParentRoute: () => ShortlistsShortlistIdRoute,
  } as any)
const STokenCCandidateIdRoute = STokenCCandidateIdRouteImport.update({
  id: '/c/$candidateId',
  path: '/c/$candidateId',
  getParentRoute: () => STokenRoute,
} as any)
const STokenAnalysisCandidateIdRoute =
  STokenAnalysisCandidateIdRouteImport.update({
    id: '/analysis/$candidateId',
    path: '/analysis/$candidateId',
    getParentRoute: () => STokenRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRoute
  '/team': typeof TeamRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/candidates/new': typeof CandidatesNewRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/pdf/$candidateId': typeof PdfCandidateIdRoute
  '/s/$token': typeof STokenRouteWithChildren
  '/shortlists/$shortlistId': typeof ShortlistsShortlistIdRouteWithChildren
  '/shortlists/new': typeof ShortlistsNewRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/shortlists/': typeof ShortlistsIndexRoute
  '/s/$token/': typeof STokenIndexRoute
  '/shortlists/$shortlistId/': typeof ShortlistsShortlistIdIndexRoute
  '/s/$token/analysis/$candidateId': typeof STokenAnalysisCandidateIdRoute
  '/s/$token/c/$candidateId': typeof STokenCCandidateIdRoute
  '/shortlists/$shortlistId/analysis/$candidateId': typeof ShortlistsShortlistIdAnalysisCandidateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRoute
  '/team': typeof TeamRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/candidates/new': typeof CandidatesNewRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/pdf/$candidateId': typeof PdfCandidateIdRoute
  '/shortlists/new': typeof ShortlistsNewRoute
  '/candidates': typeof CandidatesIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/shortlists': typeof ShortlistsIndexRoute
  '/s/$token': typeof STokenIndexRoute
  '/shortlists/$shortlistId': typeof ShortlistsShortlistIdIndexRoute
  '/s/$token/analysis/$candidateId': typeof STokenAnalysisCandidateIdRoute
  '/s/$token/c/$candidateId': typeof STokenCCandidateIdRoute
  '/shortlists/$shortlistId/analysis/$candidateId': typeof ShortlistsShortlistIdAnalysisCandidateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRoute
  '/team': typeof TeamRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/candidates/new': typeof CandidatesNewRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/pdf/$candidateId': typeof PdfCandidateIdRoute
  '/s/$token': typeof STokenRouteWithChildren
  '/shortlists/$shortlistId': typeof ShortlistsShortlistIdRouteWithChildren
  '/shortlists/new': typeof ShortlistsNewRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/shortlists/': typeof ShortlistsIndexRoute
  '/s/$token/': typeof STokenIndexRoute
  '/shortlists/$shortlistId/': typeof ShortlistsShortlistIdIndexRoute
  '/s/$token/analysis/$candidateId': typeof STokenAnalysisCandidateIdRoute
  '/s/$token/c/$candidateId': typeof STokenCCandidateIdRoute
  '/shortlists/$shortlistId/analysis/$candidateId': typeof ShortlistsShortlistIdAnalysisCandidateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compare'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tags'
    | '/team'
    | '/candidates/$candidateId'
    | '/candidates/new'
    | '/clients/$clientId'
    | '/clients/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/pdf/$candidateId'
    | '/s/$token'
    | '/shortlists/$shortlistId'
    | '/shortlists/new'
    | '/candidates/'
    | '/clients/'
    | '/jobs/'
    | '/shortlists/'
    | '/s/$token/'
    | '/shortlists/$shortlistId/'
    | '/s/$token/analysis/$candidateId'
    | '/s/$token/c/$candidateId'
    | '/shortlists/$shortlistId/analysis/$candidateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compare'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tags'
    | '/team'
    | '/candidates/$candidateId'
    | '/candidates/new'
    | '/clients/$clientId'
    | '/clients/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/pdf/$candidateId'
    | '/shortlists/new'
    | '/candidates'
    | '/clients'
    | '/jobs'
    | '/shortlists'
    | '/s/$token'
    | '/shortlists/$shortlistId'
    | '/s/$token/analysis/$candidateId'
    | '/s/$token/c/$candidateId'
    | '/shortlists/$shortlistId/analysis/$candidateId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/compare'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tags'
    | '/team'
    | '/candidates/$candidateId'
    | '/candidates/new'
    | '/clients/$clientId'
    | '/clients/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/pdf/$candidateId'
    | '/s/$token'
    | '/shortlists/$shortlistId'
    | '/shortlists/new'
    | '/candidates/'
    | '/clients/'
    | '/jobs/'
    | '/shortlists/'
    | '/s/$token/'
    | '/shortlists/$shortlistId/'
    | '/s/$token/analysis/$candidateId'
    | '/s/$token/c/$candidateId'
    | '/shortlists/$shortlistId/analysis/$candidateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TagsRoute: typeof TagsRoute
  TeamRoute: typeof TeamRoute
  CandidatesCandidateIdRoute: typeof CandidatesCandidateIdRoute
  CandidatesNewRoute: typeof CandidatesNewRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsNewRoute: typeof JobsNewRoute
  PdfCandidateIdRoute: typeof PdfCandidateIdRoute
  STokenRoute: typeof STokenRouteWithChildren
  ShortlistsShortlistIdRoute: typeof ShortlistsShortlistIdRouteWithChildren
  ShortlistsNewRoute: typeof ShortlistsNewRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ShortlistsIndexRoute: typeof ShortlistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlists/': {
      id: '/shortlists/'
      path: '/shortlists'
      fullPath: '/shortlists/'
      preLoaderRoute: typeof ShortlistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlists/new': {
      id: '/shortlists/new'
      path: '/shortlists/new'
      fullPath: '/shortlists/new'
      preLoaderRoute: typeof ShortlistsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlists/$shortlistId': {
      id: '/shortlists/$shortlistId'
      path: '/shortlists/$shortlistId'
      fullPath: '/shortlists/$shortlistId'
      preLoaderRoute: typeof ShortlistsShortlistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf/$candidateId': {
      id: '/pdf/$candidateId'
      path: '/pdf/$candidateId'
      fullPath: '/pdf/$candidateId'
      preLoaderRoute: typeof PdfCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/new': {
      id: '/candidates/new'
      path: '/candidates/new'
      fullPath: '/candidates/new'
      preLoaderRoute: typeof CandidatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$candidateId': {
      id: '/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof CandidatesCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlists/$shortlistId/': {
      id: '/shortlists/$shortlistId/'
      path: '/'
      fullPath: '/shortlists/$shortlistId/'
      preLoaderRoute: typeof ShortlistsShortlistIdIndexRouteImport
      parentRoute: typeof ShortlistsShortlistIdRoute
    }
    '/s/$token/': {
      id: '/s/$token/'
      path: '/'
      fullPath: '/s/$token/'
      preLoaderRoute: typeof STokenIndexRouteImport
      parentRoute: typeof STokenRoute
    }
    '/shortlists/$shortlistId/analysis/$candidateId': {
      id: '/shortlists/$shortlistId/analysis/$candidateId'
      path: '/analysis/$candidateId'
      fullPath: '/shortlists/$shortlistId/analysis/$candidateId'
      preLoaderRoute: typeof ShortlistsShortlistIdAnalysisCandidateIdRouteImport
      parentRoute: typeof ShortlistsShortlistIdRoute
    }
    '/s/$token/c/$candidateId': {
      id: '/s/$token/c/$candidateId'
      path: '/c/$candidateId'
      fullPath: '/s/$token/c/$candidateId'
      preLoaderRoute: typeof STokenCCandidateIdRouteImport
      parentRoute: typeof STokenRoute
    }
    '/s/$token/analysis/$candidateId': {
      id: '/s/$token/analysis/$candidateId'
      path: '/analysis/$candidateId'
      fullPath: '/s/$token/analysis/$candidateId'
      preLoaderRoute: typeof STokenAnalysisCandidateIdRouteImport
      parentRoute: typeof STokenRoute
    }
  }
}

interface STokenRouteChildren {
  STokenIndexRoute: typeof STokenIndexRoute
  STokenAnalysisCandidateIdRoute: typeof STokenAnalysisCandidateIdRoute
  STokenCCandidateIdRoute: typeof STokenCCandidateIdRoute
}

const STokenRouteChildren: STokenRouteChildren = {
  STokenIndexRoute: STokenIndexRoute,
  STokenAnalysisCandidateIdRoute: STokenAnalysisCandidateIdRoute,
  STokenCCandidateIdRoute: STokenCCandidateIdRoute,
}

const STokenRouteWithChildren =
  STokenRoute._addFileChildren(STokenRouteChildren)

interface ShortlistsShortlistIdRouteChildren {
  ShortlistsShortlistIdIndexRoute: typeof ShortlistsShortlistIdIndexRoute
  ShortlistsShortlistIdAnalysisCandidateIdRoute: typeof ShortlistsShortlistIdAnalysisCandidateIdRoute
}

const ShortlistsShortlistIdRouteChildren: ShortlistsShortlistIdRouteChildren = {
  ShortlistsShortlistIdIndexRoute: ShortlistsShortlistIdIndexRoute,
  ShortlistsShortlistIdAnalysisCandidateIdRoute:
    ShortlistsShortlistIdAnalysisCandidateIdRoute,
}

const ShortlistsShortlistIdRouteWithChildren =
  ShortlistsShortlistIdRoute._addFileChildren(
    ShortlistsShortlistIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TagsRoute: TagsRoute,
  TeamRoute: TeamRoute,
  CandidatesCandidateIdRoute: CandidatesCandidateIdRoute,
  CandidatesNewRoute: CandidatesNewRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsNewRoute: JobsNewRoute,
  PdfCandidateIdRoute: PdfCandidateIdRoute,
  STokenRoute: STokenRouteWithChildren,
  ShortlistsShortlistIdRoute: ShortlistsShortlistIdRouteWithChildren,
  ShortlistsNewRoute: ShortlistsNewRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  ShortlistsIndexRoute: ShortlistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
