
ALTER TABLE public.candidates
  ADD COLUMN IF NOT EXISTS area text,
  ADD COLUMN IF NOT EXISTS state text,
  ADD COLUMN IF NOT EXISTS country text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS seniority text,
  ADD COLUMN IF NOT EXISTS current_company text,
  ADD COLUMN IF NOT EXISTS headline text,
  ADD COLUMN IF NOT EXISTS mini_bio text,
  ADD COLUMN IF NOT EXISTS full_bio text,
  ADD COLUMN IF NOT EXISTS executive_summary jsonb,
  ADD COLUMN IF NOT EXISTS specialties jsonb,
  ADD COLUMN IF NOT EXISTS main_results jsonb,
  ADD COLUMN IF NOT EXISTS achievements jsonb,
  ADD COLUMN IF NOT EXISTS main_case jsonb,
  ADD COLUMN IF NOT EXISTS strengths jsonb,
  ADD COLUMN IF NOT EXISTS work_style text,
  ADD COLUMN IF NOT EXISTS professional_moment jsonb,
  ADD COLUMN IF NOT EXISTS motivators jsonb,
  ADD COLUMN IF NOT EXISTS trajectory jsonb,
  ADD COLUMN IF NOT EXISTS education jsonb,
  ADD COLUMN IF NOT EXISTS courses jsonb,
  ADD COLUMN IF NOT EXISTS languages jsonb,
  ADD COLUMN IF NOT EXISTS competencies jsonb,
  ADD COLUMN IF NOT EXISTS additional_info jsonb,
  ADD COLUMN IF NOT EXISTS internal_notes text,
  ADD COLUMN IF NOT EXISTS inconsistencies jsonb,
  ADD COLUMN IF NOT EXISTS ai_profile jsonb,
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'rascunho',
  ADD COLUMN IF NOT EXISTS archived_at timestamptz;

CREATE INDEX IF NOT EXISTS candidates_created_by_idx ON public.candidates(created_by);
CREATE INDEX IF NOT EXISTS candidates_status_idx ON public.candidates(status);
